import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { Footer, Header } from '../components';
export const metadata: Metadata = { title: 'Leadership Team', description: 'Meet the leadership team behind Leucine Lock DX.' };
const team = [
  {name:'Brian Bentley', role:'Chief Executive Officer', image:'/team-brian.jpg', facts:['Serial healthcare entrepreneur with 25+ years in healthcare and life sciences','Leads venture formation, commercialization strategy, and capital development','Experienced company builder for diagnostic businesses']},
  {name:'Devin Connor', role:'President', image:'/team-devin.png', facts:['Healthcare executive with 18+ years spanning operations and commercial strategy','Experience in product development and scaling diagnostic and life-science businesses','Leads execution and go-to-market strategy']},
  {name:'Dr. Jonathon Hill, PhD', role:'VP, Science & Technology', image:'/team-jonathon.jpeg', facts:['Inventor of the Leucine Lock platform; BYU associate professor and Fulbright Scholar','Expertise in protein engineering, molecular genetics, structural biology, bioinformatics, and liquid biopsy','Previous co-founder and board member']}
];
export default function Team(){return <main id="main-content"><Header/><section className="pageHero teamHero"><div><p className="eyebrow">Leadership team</p><h1>Scientific depth. Commercial discipline.</h1><p className="lead">Leucine Lock DX brings together company-building experience, healthcare commercialization, and molecular biosensor expertise.</p></div></section><section className="teamGrid section">{team.map((person,i)=><article className="person" key={person.name}><div className="portrait"><Image src={person.image} alt={person.name} fill sizes="(max-width: 560px) calc(100vw - 80px), (max-width: 900px) 36vw, 360px"/><span>0{i+1}</span></div><h2>{person.name}</h2><p className="role">{person.role}</p><ul>{person.facts.map(f=><li key={f}>{f}</li>)}</ul></article>)}</section><section className="contactStrip"><div><p className="eyebrow">Connect</p><h2>Meet the team behind the platform.</h2></div><Link className="button light" href="/contact">Contact <span>↗</span></Link></section><Footer/></main>}
