import type { Metadata } from 'next';
import { Footer, Header, Molecule } from '../components';
export const metadata: Metadata = { title: 'Technology', description: 'How the Leucine Lock biosensor platform converts target recognition into an amplified, flexible diagnostic readout.' };

export default function Technology() { return <main><Header/>
  <section className="pageHero techHero"><div><p className="eyebrow">Technology</p><h1>A molecular switch for faster, more sensitive biosensing.</h1><p className="lead">Leucine Lock is a modular biosensor concept: recognition chemistry finds the target, a controlled molecular interaction activates the system, and an enzyme-linked response amplifies the signal.</p></div><Molecule compact/></section>
  <section className="mechanism section"><div className="sectionIntro"><p className="eyebrow">The mechanism</p><h2>Four engineered layers. One readable answer.</h2></div><div className="mechanismRows">
    <article><span>01</span><div><h3>Target-specific recognition</h3><p>A single-chain variable fragment (scFv)—an engineered antibody fragment—provides the target recognition layer. Changing that recognition element allows the architecture to be adapted for different analytes.</p></div></article>
    <article><span>02</span><div><h3>Leucine Lock control</h3><p>The Leucine Lock motif is designed to control enzyme activity until target binding changes the molecular configuration. That controlled transition links recognition to activation.</p></div></article>
    <article><span>03</span><div><h3>Enzymatic amplification</h3><p>Once activated, the enzyme can produce many detectable output molecules. The deck describes a development target of greater than 10–100× amplification, improving the visibility of low-level biological signals.</p></div></article>
    <article><span>04</span><div><h3>Application-specific readout</h3><p>The amplified result can be coupled to color, luminescence, or electrical detection. This supports simple qualitative tests and instrumented quantitative measurements.</p></div></article>
  </div></section>
  <section className="designSpace"><div><p className="eyebrow">Platform design space</p><h2>Tunable where the assay needs it.</h2></div><div className="designGrid"><article><b>Targets</b><span>Bacteria</span><span>Viruses</span><span>Protein analytes</span></article><article><b>Readouts</b><span>Color</span><span>Light</span><span>Electrical</span></article><article><b>Result types</b><span>Qualitative</span><span>Quantitative</span><span>Multiplex panels</span></article><article><b>Formats</b><span>Tube tests</span><span>Portable readers</span><span>Continuous monitors</span></article></div></section>
  <section className="useCases section"><div className="sectionIntro"><p className="eyebrow">Potential applications</p><h2>From a ten-minute tube test to continuous measurement.</h2><p>Platform concepts in the company deck include viral detection, respiratory disease panels, and quantitative insulin detection. Each application requires its own assay development and validation.</p></div><div className="useCaseLine"><div><span>Sample</span></div><i/><div><span>Recognition</span></div><i/><div><span>Amplification</span></div><i/><div><span>Answer</span></div></div></section>
  <section className="contactStrip"><div><p className="eyebrow">Explore an application</p><h2>Bring us the diagnostic challenge.</h2></div><a className="button light" href="mailto:brian@diagnosticventures.net?subject=Leucine%20Lock%20technology%20inquiry">Start a conversation <span>↗</span></a></section>
  <Footer/>
</main> }
